spring:
  application:
    name: clear footprint

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/clearfootprint?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8}
    username: ${SPRING_DATASOURCE_USERNAME:cfp}
    password: ${SPRING_DATASOURCE_PASSWORD:cfp_pw}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

external:
  ai:
    base-url: ${EXTERNAL_AI_BASE_URL:https://api.example-ai.com}
  activity:
    base-url: ${EXTERNAL_ACTIVITY_BASE_URL:https://api.example-activity.com}

---
spring:
  config:
    activate:
      on-profile: prod
    import: "application-secret.yml" # 이 부분 추가
